spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reservation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: reser
    password: 1234qwer!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  profiles:
    active: local

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  jwt:
    header: Authorization
    prefix: Bearer
    secret: cGxheWdyb3VuZC1zcHJpbmctYm9vdC10ZWFtcHJvamVjdC1sb2dpbi1qd3Qtc2VjcmV0LWtleQo=
    accessToken-valid-time: 1800000 # 30min
    refreshToken-valid-time: 7200000 # 2hour

logging:
  level:
    root: INFO